apiVersion: apps/v1
kind: Deployment
metadata:
  name: portero
spec:
  replicas: 1
  selector:
    matchLabels:
      app: portero
  template:
    metadata:
      labels:
        app:
          portero
    spec:
      containers:
      - name: portero
        image: sebastiancharras/portero
        ports:
        - containerPort: 80
